# Generated by Django 5.2.5 on 2025-08-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0002_shoppinglist_favoriterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='meal_breakdown_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='meal_type_summary_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
