# Generated by Django 5.2.5 on 2025-08-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0003_shoppinglist_meal_breakdown_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteRecipe',
        ),
    ]
