# Generated by Django 5.2.5 on 2025-08-16 03:13

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.models.AccountManager()),
            ],
        ),
    ]
